version: '3.7'

services:
  zigglybot:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    image: zigglybot
    container_name: zigglybot
    networks:
      - zigglybot_network
    stdin_open: true
    tty: true
    env_file:
      - ../.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ../dist:/usr/dist

networks:
  zigglybot_network:
