version: '3.7'

services:
  zigglybot_dev:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    image: zigglybot_dev
    container_name: zigglybot_dev
    networks:
      - zigglybot_dev_network
    stdin_open: true
    tty: true
    depends_on:
      zigglybot_db:
        condition: service_healthy
    env_file:
      - ../.env
    volumes:
      - ../dist:/usr/dist
      - ../node_modules:/usr/node_modules

  zigglybot_db:
    image: postgres:15.1-alpine
    container_name: zigglybot_db_dev
    environment:
      - POSTGRES_DB=zigglybot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - zigglybot_dev_network
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  zigglybot_dev_network:
