name: 'test'

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      LOGGER_LEVEL: debug
      DISCORD_TOKEN: DISCORD_TOKEN
      CLIENT_ID: CLIENT_ID
      GUILD_ID: GUILD_ID

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
